name: Code Quality
on: push
jobs:
    code-quality:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - run: cargo test
            - run: cargo clippy -- -D warnings
            - run: cargo fmt -- --check